### ISSUE TITLE
Py3k support?

### ISSUE THREAD

**Issue by tiggreen** [HubSpot/hapipy#62]
Hey guys, is there any chance you will support py3k in a near future? Thanks.

**Comment by trjordan** [comment]
I took a hack at this: https://github.com/10stories/hapipy

I ran 2to3 and fixed a bunch of bytes/string ambiguity. The tests pass on Python 3.4.

No promises, but maybe a better starting point!

**Comment by yprez** [comment]
Also Python 2.6 support ended in **2013**. It's much more important to support Python 3 at this point...

@tiggreen I'll try to continue from your branch if you don't mind, it looks good...

@HubSpot, @prior - Is there a chance to get this merged if all tests pass on Python3.4+ as well as 2.7 (maybe 2.6 too)?
